### ISSUE TITLE
Uploader inside Form submits automatically

### ISSUE THREAD

**Issue by ssatz** [PrimitiveSocial/rainbow#1]
Hello,

Thanks for the wonderful components. I was trying in my local. 
Upload component inside form automatically submits.
Please use prevent for all click . 

Let me know if you need to pull a request. 

Best Regards,
sathish kumar

**Comment by elie-primitivesocial** [comment]
@ssatz Hey thanks for the feedback! 
Issue fixed here https://github.com/PrimitiveSocial/rainbow/commit/8ee2f6039c78f5e7f3ce420fcfdbe0499a0fca82

Also added  a new component `<multi-select>`, works like a multiple tag input selector, check it out ;)
